/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_board_serial                   20
#define gattdb_board_rev                      22
#define gattdb_firmware_rev                   24
#define gattdb_system_id                      26
#define gattdb_garage_access                  29
#define gattdb_ota_control                    33
#define gattdb_hall_state                     36
#define gattdb_hall_field_strength            39
#define gattdb_hall_control_point             42
#define gattdb_aio_digital_in                 45
#define gattdb_aio_num_of_digitals_in         48
#define gattdb_aio_digital_out                50
#define gattdb_aio_num_of_digitals_out        52
#define gattdb_es_temperature                 55
#define gattdb_es_humidity                    57
#define gattdb_es_uvindex                     59
#define gattdb_es_ambient_light               61
#define gattdb_batt_measurement               64
#define gattdb_power_source_type              68
#define gattdb_imu_acceleration               71
#define gattdb_imu_orientation                74
#define gattdb_imu_control_point              77


#endif // __GATT_DB_H
