/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_board_serial                   20
#define gattdb_board_rev                      22
#define gattdb_firmware_rev                   24
#define gattdb_system_id                      26
#define gattdb_ota_control                    29
#define gattdb_hall_state                     32
#define gattdb_hall_field_strength            35
#define gattdb_hall_control_point             38
#define gattdb_aio_digital_in                 41
#define gattdb_aio_num_of_digitals_in         44
#define gattdb_aio_digital_out                46
#define gattdb_aio_num_of_digitals_out        48
#define gattdb_es_temperature                 51
#define gattdb_es_humidity                    53
#define gattdb_es_uvindex                     55
#define gattdb_es_ambient_light               57
#define gattdb_batt_measurement               60
#define gattdb_power_source_type              64
#define gattdb_imu_acceleration               67
#define gattdb_imu_orientation                70
#define gattdb_imu_control_point              73


#endif // __GATT_DB_H
